### ISSUE TITLE
系统在pause一个job后无法再次登录

### ISSUE THREAD

**Issue by nonbotanist** [dxc-bba/yardman#66]
重现步骤：
1. 登录
2. 在完成的job上点击pause，然后确定。
3. 点击logout
4.重新使用admin登录
5.无法进入系统。且无任何后台报错。
重现次数：100%
正常logout=>login 结果 ok

**Comment by nonbotanist** [comment]
当关闭浏览器的时候，后台提示：
[29/Dec/2018 10:59:50] "POST /loginSubmit HTTP/1.1" 200 21
[29/Dec/2018 10:59:50] "POST /loginSubmit HTTP/1.1" 200 21
[29/Dec/2018 10:59:50] "POST /loginSubmit HTTP/1.1" 200 21
[29/Dec/2018 10:59:51] "POST /loginSubmit HTTP/1.1" 200 21
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.199.178.190', 50780)
Exception happened during processing of request from ('10.199.178.190', 50779)
----------------------------------------
Exception happened during processing of request from ('10.199.178.190', 50781)
Traceback (most recent call last):
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 717, in __init__
    self.handle()
Traceback (most recent call last):
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\site-packages\django-2.1.3-py3.7.egg\django\core\servers\basehttp.py", line 139, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
Traceback (most recent call last):
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 717, in __init__
    self.handle()
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 717, in __init__
    self.handle()
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\site-packages\django-2.1.3-py3.7.egg\django\core\servers\basehttp.py", line 139, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\site-packages\django-2.1.3-py3.7.egg\django\core\servers\basehttp.py", line 139, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
----------------------------------------
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------

**Comment by AaronDeng0531** [comment]
done
