### ISSUE TITLE
DD cleanup tool进不去

### ISSUE THREAD

**Issue by AaronDeng0531** [dxc-bba/yardman#75]
DD log：
D:\cleanTool>python manage.py runserver 0.0.0.0:8000 --insecure
Performing system checks...

rootPath:\\nv19100800\
recycleMainPath:\\nv19100004\IMDC_DD_BBT-53_Terminal\dd_rc
initLatestScheduler
Active indicator for toolsTrue
not TEST_INDICATOR_SCHEDULER
cleanupSchedule.cleanupDay0
cleanupSchedule.cleanupHour15
cleanupSchedule.cleanupMinute0
start scheduler
System check identified no issues (0 silenced).
February 10, 2019 - 17:09:01
Django version 2.1.3, using settings 'cleanTool.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.
[10/Feb/2019 17:09:05] "GET / HTTP/1.1" 200 2831
[10/Feb/2019 17:09:05] "GET /static/css/login.css HTTP/1.1" 200 1475
[10/Feb/2019 17:09:05] "GET /static/css/style.css HTTP/1.1" 200 9563
[10/Feb/2019 17:09:05] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 121200
[10/Feb/2019 17:09:05] "GET /static/css/iconfont.css HTTP/1.1" 200 10195
[10/Feb/2019 17:09:06] "GET /static/bootstrap/js/bootstrap.min.js HTTP/1.1" 200 37045
[10/Feb/2019 17:09:06] "GET /static/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
[10/Feb/2019 17:09:06] "GET /static/js/login.js HTTP/1.1" 200 1241
[10/Feb/2019 17:09:06] "GET /static/js/bootbox.min.js HTTP/1.1" 200 9972
[10/Feb/2019 17:09:06] "GET /static/js/common.js HTTP/1.1" 200 480
[10/Feb/2019 17:09:06] "GET /static/image/logo.png HTTP/1.1" 200 21713
[10/Feb/2019 17:09:06] "GET /static/image/mini.png HTTP/1.1" 200 13113
[10/Feb/2019 17:09:06] "GET /static/image/login-logo.png HTTP/1.1" 200 91058
[10/Feb/2019 17:09:06] "GET /favicon.ico HTTP/1.1" 302 0
[10/Feb/2019 17:09:06] "GET /static/image/favicon.ico HTTP/1.1" 200 21713
[10/Feb/2019 17:09:09] "POST /loginSubmit HTTP/1.1" 200 21
Internal Server Error: /jobs/
Traceback (most recent call last):
  File "C:\Users\vs002292\AppData\Local\Programs\Python\Python37\lib\shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vs002292\AppData\Local\Programs\Python\Python37\lib\site-packages\django-2.1.3-py3.7.egg\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\vs002292\AppData\Local\Programs\Python\Python37\lib\site-packages\django-2.1.3-py3.7.egg\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\vs002292\AppData\Local\Programs\Python\Python37\lib\site-packages\django-2.1.3-py3.7.egg\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\cleanTool\cleanToolModule\views.py", line 240, in jobs
    'history': historyStatics()
  File "D:\cleanTool\cleanToolModule\views.py", line 139, in historyStatics
    toolsScheduler = toolsSchedulerFile['main']
  File "C:\Users\vs002292\AppData\Local\Programs\Python\Python37\lib\shelve.py", line 114, in __getitem__
    value = Unpickler(f).load()
EOFError: Ran out of input
[10/Feb/2019 17:09:10] "GET /jobs/ HTTP/1.1" 500 79373
![1](https://user-images.githubusercontent.com/46098884/52542688-65c5e080-2ddd-11e9-97b5-b31d9ba3ee14.JPG)

**Comment by AaronDeng0531** [comment]
![1](https://user-images.githubusercontent.com/46098884/52542713-a32a6e00-2ddd-11e9-96b4-2bfa3108edeb.JPG)

**Comment by AaronDeng0531** [comment]
done
