### ISSUE TITLE
TX cleanup tool pending在登陆界面

### ISSUE THREAD

**Issue by AaronDeng0531** [dxc-bba/yardman#76]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\site-packages\apscheduler-3.5.3-py3.7.egg\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\cleanTool\cleanToolModule\cleanupCore.py", line 161, in cleanJob
    updateMonitor(cleanupJob, newExceptions, scanFilesCount)
  File "D:\cleanTool\cleanToolModule\cleanupCore.py", line 462, in updateMonitor
    toolsScheduler = toolsSchedulerFile['main']
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
  File "C:\Users\vs002291\AppData\Local\Programs\Python\Python37\lib\dbm\dumb.py", line 153, in __getitem__
    pos, siz = self._index[key]     # may raise KeyError
KeyError: b'main'
[13/Feb/2019 12:10:05] "POST /loginSubmit HTTP/1.1" 200 21
[13/Feb/2019 12:15:45] "GET / HTTP/1.1" 200 2831
[13/Feb/2019 12:15:55] "POST /loginSubmit HTTP/1.1" 200 21
[13/Feb/2019 12:15:58] "POST /loginSubmit HTTP/1.1" 200 21
[13/Feb/2019 12:16:30] "POST /loginSubmit HTTP/1.1" 200 21

**Comment by AaronDeng0531** [comment]
done after deployment again
